version: "3"

interval: 100ms

env:
  PGO_DATA_DIR: tmp/pgo-data
  BIN_EXTRAS: "--features build-binary --bin timsquery"

dotenv: [".env"]

tasks:
  default:
    watch: true
    sources:
      - "src/**/*.rs"
    cmds:
      - task: bin-build
      - task: lib-build
      - task: test
      - task: fmt
      - task: clippy

  bin-build:
    cmds:
      - cargo build $BIN_EXTRAS

  bin-build-release:
    deps: [test, fmt]
    sources:
      - "src/**/*.rs"
    cmds:
      - cargo b --release --features build-binary --bin timsquery

  lib-build:
    cmds:
      - cargo build --lib

  license_check:
    cmds:
      - cargo deny check

  test:
    cmds:
      - cargo test

  fmt:
    cmds:
      - cargo +nightly fmt

  clippy:
    cmds:
      - cargo clippy {{.CLI_ARGS}}

  bench:
    cmds:
      - task: bench-build
      - task: bench-small-data
      - task: bench-large-data

  bench-build:
    sources:
      - "src/**/*.rs"
    cmds:
      - cargo b --release --features bench --bin benchmark_indices

  bench-small-data:
    deps: [bench-build]
    sources:
      - "src/**/*.rs"
      - "data/230510_PRTC_13_S1-B1_1_12817.d"
      - "benches/plot_bench.py"

    cmds:
      - SKIP_SLOW=1 SKIP_BUILD=1 RUST_BACKTRACE=full TIMS_DATA_FILE=./data/230510_PRTC_13_S1-B1_1_12817.d ./target/release/benchmark_indices
      - uv run benches/plot_bench.py data/benchmark_results_230510_PRTC_13_S1-B1_1_12817.json

  bench-large-data:
    deps: [bench-build]
    sources:
      - "src/**/*.rs"
      - "data/LFQ_timsTOFPro_diaPASEF_Condition_A_Sample_Alpha_02.d"
      - "benches/plot_bench.py"
    cmds:
      - SKIP_SLOW=1 SKIP_BUILD=1 SKIP_HIGHMEM=1 RUST_BACKTRACE=full TIMS_DATA_FILE=./data/LFQ_timsTOFPro_diaPASEF_Condition_A_Sample_Alpha_02.d ./target/release/benchmark_indices
      - uv run benches/plot_bench.py data/benchmark_results_LFQ_timsTOFPro_diaPASEF_Condition_A_Sample_Alpha_02.json

  plot:
    deps: [bin-build-release]
    sources:
      - "data/sageresults/**/*.py"
    cmds:
      - for: ["expanded-raw-frame-index", "transposed-quad-index"]
        cmd: ./target/release/timsquery query-index
          --aggregator multi-cmg-stats --format pretty-json
          --raw-file-path ./data/230510_PRTC_13_S1-B1_1_12817.d
          --tolerance-settings-path "templates/tolerance_settings_narrow_rt.json"
          --elution-groups-path "./data/sageresults/ubb_elution_groups.json"
          --output-path "./data/sageresults/{{ .ITEM }}_query_results"
          --index {{ .ITEM }}
      - for: ["expanded-raw-frame-index", "transposed-quad-index"]
        cmd: cd data/sageresults &&
          uv run plot.py
          --query-results {{ .ITEM }}_query_results/results.json
          --elution-groups ubb_elution_groups.json
          --output ubb_peptide_plot{{ .ITEM }}.png

  templates:
    sources:
      - "src/**/*.rs"
    cmds:
      - cargo run $BIN_EXTRAS -- write-template --output-path templates --num-elution-groups 10000

  compiler-versions:
    requires:
      vars: [PROFDATA_EXE]
      # PROFDATA_EXE=/Users/myuser/.rustup/toolchains/{toolchain}/lib/rustlib/{arch-triple}/bin/llvm-profdata
    cmds:
      - rustc --version --verbose
      - cargo --version

  pgo-build:
    deps: [templates, compiler-versions]
    requires:
      vars: [RUST_LOG, TIMS_DATA_FILE, PROFDATA_EXE]
    cmds:
      - mkdir -p $PGO_DATA_DIR
      - rm -rf $PGO_DATA_DIR/*
      - rm -f ./target/release/timsquery
      - RUSTFLAGS="-Cprofile-generate=$PGO_DATA_DIR" cargo build --release $BIN_EXTRAS
      - ./target/release/timsquery query-index --raw-file-path $TIMS_DATA_FILE --tolerance-settings-path "templates/tolerance_settings.json" --elution-groups-path "templates/elution_groups.json" --output-path . --pretty --index transposed-quad-index --aggregator chromato-mobilogram-stat
      # TODO add more data/run types.
      # - ./target/release/timsquery mydata2.csv
      # - ./target/release/timsquery mydata3.csv
      - ls -lcth $PGO_DATA_DIR
      - $PROFDATA_EXE merge -o $PGO_DATA_DIR/merged.profdata $PGO_DATA_DIR && ls -lcth $PGO_DATA_DIR
      - RUSTFLAGS="-Cprofile-use=${PWD}/${PGO_DATA_DIR}/merged.profdata -Cllvm-args=-pgo-warn-missing-function" cargo build $BIN_EXTRAS --release
      - ./target/release/timsquery  query-index --raw-file-path $TIMS_DATA_FILE --tolerance-settings-path "templates/tolerance_settings.json" --elution-groups-path "templates/elution_groups.json" --output-path . --pretty --index transposed-quad-index --aggregator chromato-mobilogram-stat
      # TODO make this multi-platform
